services:
  db:
    networks:
      - backend
  redis:
    networks:
      - backend
  backend:
    command: scripts/run.dev.gunicorn.sh
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - REDIS_ADDR=${REDIS_ADDR:-redis}
    networks:
      - backend
