# Generated by Django 4.2.16 on 2024-11-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditIncreaseRequestModel',
            new_name='BalanceIncreaseRequestModel',
        ),
    ]
