# Generated by Django 4.2.16 on 2024-10-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_alter_recharge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='accounts.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.sellerprofile'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
