# Generated by Django 4.2.16 on 2024-11-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_balanceincreaserequestmodel_seller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceincreaserequestmodel',
            options={'ordering': ['pk']},
        ),
    ]
