# Generated by Django 4.2.16 on 2024-10-31 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0003_alter_recharge_seller_alter_transaction_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.customerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.sellerprofile')),
            ],
        ),
        migrations.RenameField(
            model_name='recharge',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
