# Generated by Django 4.2.16 on 2024-11-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusmodel',
            options={'permissions': [('can_change_status_only', 'Can only change field status')]},
        ),
    ]
